# Generated by Django 5.2 on 2025-05-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_photos/%Y/%m/%d/'),
        ),
    ]
