# Generated by Django 5.2 on 2025-05-05 11:02

import scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_lesson_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=scheduler.models.lesson_photo_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=scheduler.models.lesson_photo_path),
        ),
    ]
