# Generated by Django 5.2 on 2025-05-05 11:52

import django.db.models.deletion
import scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_lesson_thumbnail_alter_lesson_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='LessonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=scheduler.models.lesson_photo_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=scheduler.models.lesson_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='scheduler.lesson')),
            ],
        ),
    ]
