# Generated by Django 5.2 on 2025-05-05 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_lesson_photos_remove_lesson_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('tutor', 'datetime')},
        ),
    ]
