# Generated by Django 5.2 on 2025-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_duplicate_slots'),
        ('scheduler', '0005_alter_timeslot_options_and_more'),
    ]

    operations = [
    ]
