# Generated by Django 5.2 on 2025-05-06 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_merge_20250505_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='homework',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('english', 'Английский язык'), ('russian', 'Русский язык'), ('literature', 'Литература'), ('history', 'История'), ('geography', 'География'), ('other', 'Другое')], default='math', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
