# Generated by Django 5.2 on 2025-05-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_lesson_homework_lesson_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringLessonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')])),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=60)),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('english', 'Английский язык'), ('russian', 'Русский язык'), ('literature', 'Литература'), ('history', 'История'), ('geography', 'География'), ('other', 'Другое')], default='math', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
