# Generated by Django 5.2.1 on 2025-05-21 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_resourcelink_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subjects', models.JSONField(default=list, help_text='Список предметов, которые преподаёт')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_list', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связь преподаватель-ученик',
                'verbose_name_plural': 'Связи преподаватель-ученик',
                'unique_together': {('tutor', 'student')},
            },
        ),
    ]
